# -*- coding: utf-8 -*-
"""Homework2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POPdbQjdQzWwFBvY4ZsBv8BYqKWNXKs4
"""

bp_readings=[120, 137, 151, 123, 162, 173, 127, 154]
normalized_readings=[]

def normalize(bp_readings):
  min_val=min(bp_readings)
  max_val=max(bp_readings)
  denominator=max_val-min_val
  for i in bp_readings:
    numerator=i-min_val
    norm=numerator/denominator
    normalized_readings.append(norm)
  return normalized_readings

normalize(bp_readings)